# Generated by Django 4.2.9 on 2024-01-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_rename_userprofilemodel_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounttier',
            name='ability_to_generate_custom_size_mini',
            field=models.BooleanField(default=0),
        ),
    ]
