# Generated by Django 4.2.9 on 2024-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_useraccounttier_ability_to_generate_custom_size_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounttier',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
