# Generated by Django 4.2.9 on 2024-01-14 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_useraccounttier_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=30, message='The text must contain at least 30 characters.'), django.core.validators.MaxLengthValidator(limit_value=3000, message='The text cannot exceed 3000 characters.')]),
        ),
    ]
