# Generated by Django 4.2.9 on 2024-01-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_remove_userprofile_points_userprofile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users_app.useraccounttier'),
        ),
    ]
