# Generated by Django 4.2.9 on 2024-01-14 20:22

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_alter_userprofile_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='defoult_avatar.jpg', upload_to=users_app.models.user_avatar_image_path),
        ),
    ]
