# Generated by Django 4.2.9 on 2024-01-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
