# Generated by Django 4.2.1 on 2023-11-22 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniatureSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_file', models.ImageField(blank=True, upload_to=image_app.models.user_uploaded_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('short_description', models.TextField(blank=True, max_length=300, null=True)),
                ('private', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txt', models.TextField(verbose_name=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3000)])),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_app.imagemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.PositiveIntegerField(default=3000, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(3000)])),
                ('img', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_app.imagemodel')),
            ],
        ),
    ]
