# Generated by Django 4.2.9 on 2024-01-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecommentmodel',
            old_name='txt',
            new_name='text',
        ),
    ]
