# Generated by Django 4.2.9 on 2024-01-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('image_app', '0005_rename_imagemodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiniatureSizeModel',
            new_name='MiniatureSize',
        ),
    ]
