# Generated by Django 4.2.9 on 2024-01-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0006_rename_miniaturesizemodel_miniaturesize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpiringLinkModel',
            new_name='ExpiringLink',
        ),
    ]
