# Generated by Django 4.2.9 on 2024-01-07 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0007_rename_expiringlinkmodel_expiringlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=30, message='The text must contain at least 30 characters.'), django.core.validators.MaxLengthValidator(limit_value=3000, message='The text cannot exceed 3000 characters.')]),
        ),
    ]
