# Generated by Django 4.2.9 on 2024-01-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0009_rename_image_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='beans',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
