# Generated by Django 4.2.9 on 2024-01-14 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_app', '0010_imagemodel_beans'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='users_likes',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
